# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-06 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='attending',
            field=models.BooleanField(default=False),
        ),
    ]
