# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-19 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20190918_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
    ]
