# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-11 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190907_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user_name',
        ),
    ]
